services:
  backend:
    build:
      context: .
      dockerfile: SmartMealCalculatorServer/Dockerfile
    container_name: smartmealcalculatorServer
    ports:
      - "5099:8080"

    networks:
      - proxy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Europe/Stockholm
    volumes:
      - /data/compose/10/SmartMealCalculatorServer:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smartmealcalculator-backend.entrypoints=http"
      - "traefik.http.routers.smartmealcalculator-backend.rule=Host(`apismartmeal.jesperhellstrom.com`)"
      - "traefik.http.middlewares.smartmealcalculator-backend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.smartmealcalculator-backend.middlewares=smartmealcalculator-backend-https-redirect"
      - "traefik.http.routers.smartmealcalculator-backend-secure.entrypoints=https"
      - "traefik.http.routers.smartmealcalculator-backend-secure.rule=Host(`apismartmeal.jesperhellstrom.com`)"
      - "traefik.http.routers.smartmealcalculator-backend-secure.tls=true"
      - "traefik.http.services.smartmealcalculator-backend.loadbalancer.server.port=8080"

  frontend:
    build:
      context: .
      dockerfile: SmartMealCalculator/Dockerfile
    container_name: smartmealcalculator
    ports:
      - "5195:80"
    networks:
      - proxy
    depends_on:
      - backend
    environment:
      - API_BASE_URL=https://apismartmeal.jesperhellstrom.com

networks:
  proxy:
    external: true